version: '3.8'
services:
  db-notificaciones:
    container_name: unicesarapp-notificaciones-db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mailsdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3321:3306'
    volumes:
      - db-notificaciones:/var/lib/mysql
      - ./database/mailsdb.sql:/docker-entrypoint-initdb.d/init.sql
  # api-notificaciones:
  #   container_name: unicesarapp-notificaciones-api
  #   image: openjdk:17-alpine
  #   depends_on:
  #     - db-notificaciones
  #   ports:
  #     - 3101:3101
  #   environment:
  #     HOST: db-notificaciones
  #     PORT: 3306
  #     USER: root
  #     PASSWORD: root
  #   links:
  #     - db-notificaciones
  #   volumes:
  #     - ./ms:/opt/ms
  #   entrypoint: 
  #     ["/opt/openjdk-17/bin/java", "-jar", "/opt/ms/unicesarapp-notificaciones-0.0.1.jar", "--logging.file.name=/opt/ms/unicesarapp-notificaciones-0.0.1.log"]
volumes:
  db-notificaciones:
    driver: local
